[Variables]
TimeFormat=#24Hour#
ClockName=#Clock#
DayLightSavings=0
24Hour=%H:%M
12Hour=%I:%M %p
updatespeed=1
hidesecondhand=0
ShowSeconds=60
ShowSecondsDot=1
CityName1=Tokyo
CityZone1=+20
NightEnds=7
NightStarts=22
Height=220

;Your Antivirus likely blocked the easy configuration tool, how unlucky for you! Fortunately you can still edit the above value.
;Refresh the skin after saving this file.
;Make sure ShowSeconds is either 60 (disable) or 1 (enable), anything else might crash Rainmeter
