[Variables]

Width=435
Height=800
Color1=255,255,255,150
BackgroundOpacity1=188
Color2=255,255,255,150
BackgroundOpacity2=249
gradientangle=90

showbordertopbottom=1
showborderleftright=1
ColorBorder=255,255,255
borderwidth=1
RoundedEdges=0
EnableAero=0
EnableBlur=0
BackgroundOpacity=1
BackgroundImage=
BackgroundImageHidden=1
UseWin10Blur=None
Opacity=129
Shadow=
CornerRadius=40
StrokeWidth=0
StrokeColor=179,16,16
UseWin11Blur=None
