[ShortcutsE]
Meter=String
MeterStyle=Side
Text=#Shortcuts#
Hidden=0
Y=(92)*#scaledpi#
x=(25)*#scaledpi#



[block]
w=(40)*#scaledpi#
h=(40)*#scaledpi#
X=(6)*#scaledpi#R
y=r
MouseActionCursor=1
LeftMouseUpAction=!ToggleConfig "BigSur\Shortcuts\#currentsection#" "Item3.ini"
ToolTipText=#currentsection#
imagename=#@#\Graphics\Thumbs\Shortcuts\#currentsection#.png



[7-zip]
Meter=Image
x=(225)*#scaledpi#
y=(40)*#scaledpi#
MeterStyle=block

[Anydesk]
Meter=Image
MeterStyle=block

[Audacity]
Meter=Image
MeterStyle=block

[battlenet]
Meter=Image
MeterStyle=block


[blender]
Meter=Image
MeterStyle=block




[Chrome]
Meter=Image
MeterStyle=block



[Discord]
Meter=Image
MeterStyle=block

[Edge]
Meter=Image
MeterStyle=block


[Essentials]
Meter=Image
MeterStyle=block


[Evernote]
Meter=Image
MeterStyle=block


[Excel]
Meter=Image
MeterStyle=block
x=(225)*#scaledpi#
y=(7)*#scaledpi#R


[filezilla]
Meter=Image
MeterStyle=block

[firefox]
Meter=Image
MeterStyle=block


[gimp]
Meter=Image
MeterStyle=block



[illustrator]
Meter=Image
MeterStyle=block



[indesign]
Meter=Image
MeterStyle=block

[lightroom]
Meter=Image
MeterStyle=block


[notepad]
Meter=Image
MeterStyle=block


[onenote]
Meter=Image
MeterStyle=block


[opera]
Meter=Image
MeterStyle=block


[origin]
Meter=Image
MeterStyle=block
x=(225)*#scaledpi#
y=(7)*#scaledpi#R

[outlook]
Meter=Image
MeterStyle=block


[paint]
Meter=Image
MeterStyle=block



[photoshop]
Meter=Image
MeterStyle=block



[plex]
Meter=Image
MeterStyle=block


[powerpoint]
Meter=Image
MeterStyle=block




[Telegram]
Meter=Image
MeterStyle=block



[spotify]
Meter=Image
MeterStyle=block


[steam]
Meter=Image
MeterStyle=block



[stickynotes]
Meter=Image
MeterStyle=block


[teams]
Meter=Image
MeterStyle=block
x=(225)*#scaledpi#
y=(7)*#scaledpi#R

[teamviewer]
Meter=Image
MeterStyle=block


[VLC]
Meter=Image
MeterStyle=block


[vscode]
Meter=Image
MeterStyle=block


[word]
Meter=Image
MeterStyle=block

[winrar]
Meter=Image
MeterStyle=block


[zoom]
Meter=Image
MeterStyle=block


[ChatGPT]
Meter=Image
MeterStyle=block

[ClipStudioPaint]
Meter=Image
MeterStyle=block


[VisualStudio]
Meter=Image
MeterStyle=block

[te]
meter=string
MeterStyle=Default
y=(10)*#scaledpi#R
x=(225)*#scaledpi#
text=#SpecialPurpose#

[calculator]
Meter=Image
MeterStyle=block
x=(225)*#scaledpi#
y=(5)*#scaledpi#R

[Calendar]
Meter=Image
MeterStyle=block



[Control]
Meter=Image
MeterStyle=block


[powershell]
Meter=Image
MeterStyle=block


[darkmode]
Meter=Image
MeterStyle=block

[SunriseSunset]
Meter=Image
MeterStyle=block
LeftMouseUpAction=!ToggleConfig "BigSur\Widgets\#currentsection#" "Item3.ini"

[Custom1]
Meter=Image
MeterStyle=block

imagename=#skinspath#\bigsur\Shortcuts\#currentsection#\ReplaceThisPng.png
LeftMouseUpAction=!ToggleConfig "BigSur\Shortcuts\#currentsection#" "Item3.ini"
ToolTipText=#MakeYourOwn#

[Custom2]
Meter=Image
MeterStyle=block
imagename=#skinspath#\bigsur\Shortcuts\#currentsection#\ReplaceThisPng.png
LeftMouseUpAction=!ToggleConfig "BigSur\Shortcuts\#currentsection#" "Item3.ini"
ToolTipText=#MakeYourOwn#

[Custom3]
Meter=Image
MeterStyle=block
imagename=#skinspath#\bigsur\Shortcuts\#currentsection#\ReplaceThisPng.png
LeftMouseUpAction=!ToggleConfig "BigSur\Shortcuts\#currentsection#" "Item3.ini"
ToolTipText=#MakeYourOwn#


[Custom4]
Meter=Image
MeterStyle=block
imagename=#skinspath#\bigsur\Shortcuts\#currentsection#\ReplaceThisPng.png
LeftMouseUpAction=!ToggleConfig "BigSur\Shortcuts\#currentsection#" "Item3.ini"
ToolTipText=#MakeYourOwn#




