[WebE]
Meter=String
MeterStyle=Side
Text=#Web#
Hidden=0
Y=(119)*#scaledpi#
x=(25)*#scaledpi#



[block]
w=(42)*#scaledpi#
h=(42)*#scaledpi#
X=(6)*#scaledpi#R
y=r
MouseActionCursor=1
imagename=#@#\Graphics\mini.png
imagealpha=100
imagetint=#colorskin#



[tint]
imagetint=#textcolor2#




[1]
Meter=Image
x=(225)*#scaledpi#
y=(40)*#scaledpi#
MeterStyle=block

[2]
Meter=Image
MeterStyle=block

[3]
Meter=Image
MeterStyle=block

[4]
Meter=Image
MeterStyle=block

[5]
Meter=Image
MeterStyle=block

[6]
Meter=Image
MeterStyle=block

[7]
Meter=Image
MeterStyle=block

[8]
Meter=Image
MeterStyle=block

[9]
Meter=Image
MeterStyle=block
[10]
Meter=Image
MeterStyle=block




[11]
Meter=Image
MeterStyle=block
x=(225)*#scaledpi#
y=(7)*#scaledpi#R
[12]
Meter=Image
MeterStyle=block

[13]
Meter=Image
MeterStyle=block

[14]
Meter=Image
MeterStyle=block
[15]
Meter=Image
MeterStyle=block
[16]
Meter=Image
MeterStyle=block
[17]
Meter=Image
MeterStyle=block
[18]
Meter=Image
MeterStyle=block
[19]
Meter=Image
MeterStyle=block
[20]
Meter=Image
MeterStyle=block





[21]
Meter=Image
MeterStyle=block
x=(225)*#scaledpi#
y=(7)*#scaledpi#R

[22]
Meter=Image
MeterStyle=block

[23]
Meter=Image
MeterStyle=block

[24]
Meter=Image
MeterStyle=block
[25]
Meter=Image
MeterStyle=block
[26]
Meter=Image
MeterStyle=block
[27]
Meter=Image
MeterStyle=block
[28]
Meter=Image
MeterStyle=block
[29]
Meter=Image
MeterStyle=block
[30]
Meter=Image
MeterStyle=block



[31]
Meter=Image
MeterStyle=block
x=(225)*#scaledpi#
y=(7)*#scaledpi#R

[32]
Meter=Image
MeterStyle=block

[33]
Meter=Image
MeterStyle=block

[34]
Meter=Image
MeterStyle=block


[35]
Meter=Image
MeterStyle=block

[36]
Meter=Image
MeterStyle=block



[WebShortcut]
w=(35)*#scaledpi#
h=(35)*#scaledpi#
X=(13)*#scaledpi#R
y=r

LeftMouseUpAction=!ToggleConfig "BigSur\Web\#currentsection#" "Item3.ini"
ToolTipText=#currentsection#
imagename=#@#\Graphics\Thumbs\Web\#currentsection#.png
MouseActionCursor=1





[Netflix]
Meter=Image
MeterStyle=WebShortcut
x=(228)*#scaledpi#
y=(43)*#scaledpi#



[Google]
Meter=Image
MeterStyle=WebShortcut
[Amazon]
Meter=Image
MeterStyle=WebShortcut | tint


[YouTube]
Meter=Image
MeterStyle=WebShortcut
[Facebook]
Meter=Image
MeterStyle=WebShortcut
[Reddit]
Meter=Image
MeterStyle=WebShortcut
[Twitter]
Meter=Image
MeterStyle=WebShortcut
[Imdb]
Meter=Image
MeterStyle=WebShortcut
[Pinterest]
Meter=Image
MeterStyle=WebShortcut
[Fandom]
Meter=Image
MeterStyle=WebShortcut



[Craigslist]
Meter=Image
MeterStyle=WebShortcut
x=(228)*#scaledpi#
y=(14)*#scaledpi#R

[eBay]
Meter=Image
MeterStyle=WebShortcut
[DeviantArt]
Meter=Image
MeterStyle=WebShortcut
[Indeed]
Meter=Image
MeterStyle=WebShortcut
[Nytimes]
Meter=Image
MeterStyle=WebShortcut | tint

[Msnbc]
Meter=Image
MeterStyle=WebShortcut
[cnn]
Meter=Image
MeterStyle=WebShortcut
[weatherdotcom]
Meter=Image
MeterStyle=WebShortcut
[businessinsider]
Meter=Image
MeterStyle=WebShortcut

[theguardian]
Meter=Image
MeterStyle=WebShortcut
[msn]
Meter=Image
MeterStyle=WebShortcut | tint
x=(228)*#scaledpi#
y=(14)*#scaledpi#R



[usatoday]
Meter=Image
MeterStyle=WebShortcut | tint

[cnet]
Meter=Image
MeterStyle=WebShortcut
[spotify]
Meter=Image
MeterStyle=WebShortcut

[9gag]
Meter=Image
MeterStyle=WebShortcut | tint


[geektyper]
Meter=Image
MeterStyle=WebShortcut
[wikipedia]
Meter=Image
MeterStyle=WebShortcut | tint

[Webmd]
Meter=Image
MeterStyle=WebShortcut


[Yandex]
Meter=Image
MeterStyle=WebShortcut
[Github]
Meter=Image
MeterStyle=WebShortcut | tint


[Engadget]
Meter=Image
MeterStyle=WebShortcut
x=(228)*#scaledpi#
y=(14)*#scaledpi#R



[Yahoo]
Meter=Image
MeterStyle=WebShortcut




[Yelp]
Meter=Image
MeterStyle=WebShortcut



[walmart]
Meter=Image
MeterStyle=WebShortcut



[livescore]
Meter=Image
MeterStyle=WebShortcut



[ChatGPT]
Meter=Image
MeterStyle=WebShortcut | tint

[te]
meter=string
MeterStyle=Default
y=(32)*#scaledpi#R
x=(225)*#scaledpi#
text=#MakeYourOWn#

[Custom1]
Meter=Image
MeterStyle=block
x=(225)*#scaledpi#
y=(5)*#scaledpi#R
imagename=#skinspath#\bigsur\Web\#currentsection#\ReplaceThisPng.png
LeftMouseUpAction=!ToggleConfig "BigSur\Web\#currentsection#" "Item3.ini"
ImageTint=#IconTintSpecial#

[Custom2]
Meter=Image
MeterStyle=block
imagename=#skinspath#\bigsur\Web\#currentsection#\ReplaceThisPng.png
LeftMouseUpAction=!ToggleConfig "BigSur\Web\#currentsection#" "Item3.ini"
ImageTint=#IconTintSpecial#
[Custom3]
Meter=Image
MeterStyle=block
imagename=#skinspath#\bigsur\Web\#currentsection#\ReplaceThisPng.png
LeftMouseUpAction=!ToggleConfig "BigSur\Web\#currentsection#" "Item3.ini"
ImageTint=#IconTintSpecial#

[Custom4]
Meter=Image
MeterStyle=block
imagename=#skinspath#\bigsur\Web\#currentsection#\ReplaceThisPng.png
LeftMouseUpAction=!ToggleConfig "BigSur\Web\#currentsection#" "Item3.ini"
ImageTint=#IconTintSpecial#

[Custom5]
Meter=Image
MeterStyle=block
imagename=#skinspath#\bigsur\Web\#currentsection#\ReplaceThisPng.png
LeftMouseUpAction=!ToggleConfig "BigSur\Web\#currentsection#" "Item3.ini"
ImageTint=#IconTintSpecial#