[Variables]
Version=1.4.0
MainLanguage=English
globalblurenable=1
Structure=Structure
blurcornerradius=35
Padding=0
ScaleDpi=1
ThemeFont=SF Pro Display
HideLabels=1
SubstituteFeed="&apos;":"'","&quot;":"","&Quot;":"","&amp;":"&","&lt;br&gt;":"","![CDATA[":"","]]":"","...":"","<":"",">":"","/PRE&gt;":"","PRE&gt;":"","&lt;":"","&#39;":"'","&#228;":"ä","&#246;":"ö","&#8211;":"–"
SubstituteLink="&amp;":"&","<![CDATA[":"","]]>":""
redcolor=255,255,255,150
CodePage=0
GlobalWeatherCode=
Opacity=255
title=0
DarkMode=1
ttgallerystyle=dark
OnOff=
textcolor2=255,255,255
colorskin2=0,0,0
InlineShadow=Shadow | 2 | 2 | 3.5 | 0,0,0,150
HideUnits=1
DisplayAMPM=1
TimeFormat=%H:%M
colorskin=30,30,30
FirstTime=0
MissingComponents=!DeactivateConfig
EditManually=0
Draggable=1
opacity2=100
roundness=15
LabelColor=255,255,255
LabelOpacity=0
BlurEnabled=1
BlurType=None
BlurRound=Round
radius=23
IconTint=#textcolor2#
IconGreyscale=1
SelectedStyle=Dark

StrokeWidth=1
StrokeColor=30,30,30,100
StrokeOpacity=255
WidgetShadow=0

colorskinGrad=30,30,30
colorskinGradAngle=135
StrokeColorGrad=255,255,255,200
StrokeAngle=235
ExtrasColor=255,255,255
ExtrasOpacity=100
Latitude=39.298199
Longitude=16.253889
radiusBlurApp=23
paddingBlurApp=10


BlurIntensity=2
BlurNoResize=0
BlurZoom=1
BlurImagePath=
BlurDisabled=0
StrokeColorAngle=90
IconTintSpecial=#textcolor2#
FastBlur=1

[Default]
FontColor=#textcolor2#
FontFace=#ThemeFont#
FontSize=(11)*#scaledpi#
StringAlign=LEFT
AntiAlias=1
InlineSetting=#InlineShadow#
