[Variables]
RSS1=http://rss.cnn.com/rss/edition.rss
RSS1Name=BBC World
RSS2=http://reddit.com/.rss
RSS2Name=Reddit
RSS3=https://www.cnbc.com/id/100003114/device/rss/rss.html
RSS3Name=CNBC
RSS4=http://rss.cnn.com/rss/edition.rss
RSS4Name=CNN News
RSS5=http://www.engadget.com/rss.xml
RSS5Name=Engadget
RSSMain=https://www.cnbc.com/id/100003114/device/rss/rss.html
RSSMainName=CNBC

;Your Antivirus likely blocked the easy configuration tool, how unlucky for you! Fortunately you can still edit the above value.
;Refresh the skin after saving this file.