[Variables]
ChangeWallpaper=
WallpaperDark=#Skinspath#\BigSur\Gallery\Welcome\wall1.jpg
WallpaperLight=#Skinspath#\BigSur\Gallery\Welcome\wall0.jpg
ChangeDock=Disabled
DockDark=Big Sur Dark
DockLight=Big Sur Light
SunriseSunset=1
MinutesHourMinute1=350
DarkMode1=0

;Your Antivirus likely blocked the easy configuration tool, how unlucky for you! Fortunately you can still edit the above value.
;Refresh the skin after saving this file.
