[Variables]
PicturesFolder=%USERPROFILE%\Pictures
SlideshowSpeed=20
Subfolders=0
open=["%USERPROFILE%\Pictures"]
next=[!Refresh]
Action=#open#
showpicturestext=1
PicturesFolderText=D:\Users\User\Pictures\150 Top Quality Wallpapers
PicturesButtonAction=#open#
FramePadding=0
KeepAspectRatio=2

;Your Antivirus likely blocked the easy configuration tool, how unlucky for you! Fortunately you can still edit the above value.
;Refresh the skin after saving this file.
height=150
SmootherEdge=1
