[Variables]
langcode=en-us
rsslink=https://www.theguardian.com/world/rss
Settings=Settings
Alternative=Alternative
Close=Close
AddItems=Add Items
MoreActions=More Actions...
Greetings=Greetings
GoodMorning=Good morning
GoodAfternoon=Good afternoon
GoodEvening=Good evening
AddAnother=Add Another
Font=Font
ColorText=Color
Size=Size
DPIScaleText=DPI Scale
OpacityText=Opacity
FormatText=Format
UpdateAvailable=New update available! Click here to check it out
visualizerhint=Note: Visualizer bars are only visible when sound is playing. Click here to dismiss this message.
HideLabelsText=Hide Labels
DarkModeText=Dark Mode
24HCelsius=24H / Celsius
;change to onoff=alt for international version
OnOff=
GetMoreExtras=
SpecialPurpose=Special Purpose
Widgets=Widgets
Shortcuts=Shortcuts
Extras=Extras
About=About
Web=Web
Today=Today
ApplyTheme=Apply Theme
UnitsTooltip=For Time, Calendars and Weather
Switches=Switches
Calendar=Calendar
Moon=Moon
System=System
Mode=Mode
Greeter=Greeter
Battery=Battery
WorldClock=World Clock
Library=Library
Remote=Remote
NotesText=Notes
Photos=Photos
Timer=Timer
Weather=Weather
DigitalClock=Digital Clock
Clock=Clock
FullMoon=Full Moon
WaningGibbous=Waning Gibbous
LastQuarter=Last Quarter
WaningCrescent=Waning Crescent
NewMoon=New Moon
FirstQuarter=First Quarter
WaxingGibbous=Waxing Gibbous
WaxingCrescent=Waxing Crescent
Home=At Home

Lock=Lock
Unlock=Unlock
LightModeAt=Light Mode at
DarkModeAt=Dark Mode at

Missing1=If you see this message, it's likely your Antivirus blocked one or several important components
Missing2=This Skin is installed in limited mode, and some features won't work. We highly recommend to whitelist the blocked apps. 
Missing3=Click here for more info

Donator=Contributor
donate0=Support our work and get more stuff!
donate1=These Widgets are reserved for people who have contributed to Big Sur and
donate2=Omnimo. Help us with finding bugs, translations or donate to keep us online!

OpacityText2=BG Opacity
MakeYourOWn=Make Your Own
Custom=Custom
CountdownName=Countdown
DateTimeName=Date


Wallpaper=Use Wallpaper
ChangeNews=Change News
Till=Till

NotesRename=Notes
TimeZoneClock=Add a Timezone Clock
selectlayout=Select a layout
thankyou=Thank you!



EditSmartStack=Edit Smart Stack
SelectProgram=Select App
TopStories=Top Stories
News=News
StyleText=Style
PickStyle=Pick a Style and a Wallpaper
OnlyWin11=Only works in Win11
EnableTransparencyEffects=Enable Transparency Effects in the Control Panel
LiquidGlass=Disable Blur
WebShortcut=Web Shortcut
Application=Application
Shortcut=Shortcut
Desktop=Desktop
Help=Help
Sleep=Sleep
Logoff=Log off
Shutdown=Shutdown
Restart=Restart
Hibernate=Hibernate
Lock=Lock

Sunrise=Sunrise
Sunset=Sunset
LanguageText=Language
AdvancedStyle=Advanced Style

ApplyBlur=Apply Blur
EnableBlur=Blur (BETA)
Style=Style
TintOpacity=Tint Opacity
ColorTint=Tint Color
WeatherGps=Weather GPS
WeatherNotWorking=Weather not working?
CustomizeMore=(More options will be shown in the "Styles" section later)

GetGPS=Get GPS
Light=Light
Dark=Dark
Glass=Glass
DarkGlass=DarkGlass
Tinted=Tinted
LeftAlign=Left Align
RightAlign=Right Align
CenterAlign=Center Align
RefreshAll=Refresh All

SetFolder=Click here to set Pictures folder
NoPictures=No pictures found
SetOutput=Set Sound output to:
ToggleMute=Toggle Mute